# Generated by Django 5.0.4 on 2024-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor_shift_remove_dutyschedule_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(max_length=20),
        ),
    ]
